/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ApiVisualReviewRouteImport } from './routes/api/visual-review'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisualReviewRoute = ApiVisualReviewRouteImport.update({
  id: '/api/visual-review',
  path: '/api/visual-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/contact': typeof ContactRoute
  '/editor': typeof EditorRoute
  '/api/visual-review': typeof ApiVisualReviewRoute
}
export interface FileRoutesByTo {
  '/contact': typeof ContactRoute
  '/editor': typeof EditorRoute
  '/api/visual-review': typeof ApiVisualReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/contact': typeof ContactRoute
  '/editor': typeof EditorRoute
  '/api/visual-review': typeof ApiVisualReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/contact' | '/editor' | '/api/visual-review'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/editor' | '/api/visual-review'
  id: '__root__' | '/contact' | '/editor' | '/api/visual-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ContactRoute: typeof ContactRoute
  EditorRoute: typeof EditorRoute
  ApiVisualReviewRoute: typeof ApiVisualReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visual-review': {
      id: '/api/visual-review'
      path: '/api/visual-review'
      fullPath: '/api/visual-review'
      preLoaderRoute: typeof ApiVisualReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ContactRoute: ContactRoute,
  EditorRoute: EditorRoute,
  ApiVisualReviewRoute: ApiVisualReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
